
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action openAction1;
	private global::Gtk.Action saveAction1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Toolbar toolbar2;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Image image1;
	private global::Gtk.Image image2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Entry entry1;
	private global::Gtk.Entry entry2;
	private global::Gtk.Entry entry3;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Entry entry4;
	private global::Gtk.Entry entry5;
	private global::Gtk.Entry entry6;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Entry entry7;
	private global::Gtk.Entry entry8;
	private global::Gtk.Entry entry9;
	private global::Gtk.Label label1;
	private global::Gtk.HBox hbox4;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Image image3;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Entry entry10;
	private global::Gtk.Entry entry11;
	private global::Gtk.Entry entry12;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Entry entry13;
	private global::Gtk.Entry entry14;
	private global::Gtk.Entry entry15;
	private global::Gtk.Label label2;
	private global::Gtk.Table table1;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Image image4;
	private global::Gtk.VBox vbox8;
	private global::Gtk.Entry entry16;
	private global::Gtk.Entry entry17;
	private global::Gtk.Entry entry18;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Image image7;
	private global::Gtk.VBox vbox9;
	private global::Gtk.Entry entry19;
	private global::Gtk.Entry entry20;
	private global::Gtk.Entry entry21;
	private global::Gtk.HBox hbox7;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Image image5;
	private global::Gtk.VBox vbox10;
	private global::Gtk.Entry entry22;
	private global::Gtk.Entry entry23;
	private global::Gtk.Entry entry24;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Image image6;
	private global::Gtk.VBox vbox11;
	private global::Gtk.Entry entry25;
	private global::Gtk.Entry entry26;
	private global::Gtk.Entry entry27;
	private global::Gtk.VBox vbox12;
	private global::Gtk.Entry entry28;
	private global::Gtk.Entry entry29;
	private global::Gtk.Entry entry30;
	private global::Gtk.Label label3;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Сохранить"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Сохранить");
		w1.Add (this.saveAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Открыть"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Открыть");
		w1.Add (this.openAction, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", null, null, "gtk-open");
		w1.Add (this.openAction1, null);
		this.saveAction1 = new global::Gtk.Action ("saveAction1", null, null, "gtk-save");
		w1.Add (this.saveAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='openAction1' action='openAction1'/><toolitem name='saveAction1' action='saveAction1'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.Orientation = ((global::Gtk.Orientation)(1));
		this.toolbar2.ShowArrow = false;
		this.toolbar2.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.toolbar2.IconSize = ((global::Gtk.IconSize)(3));
		this.hbox2.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.toolbar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 2;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.WidthRequest = 300;
		this.image1.HeightRequest = 175;
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Summer_work.Отсканированный документ-4.jpg");
		this.vbox1.Add (this.image1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image2 = new global::Gtk.Image ();
		this.image2.WidthRequest = 300;
		this.image2.HeightRequest = 175;
		this.image2.Name = "image2";
		this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Summer_work.Отсканированный документ-10.jpg");
		this.vbox1.Add (this.image2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image2]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.vbox4.Add (this.entry1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entry1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.vbox4.Add (this.entry2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entry2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.vbox4.Add (this.entry3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entry3]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
		w8.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '•';
		this.vbox3.Add (this.entry4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry4]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry ();
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '•';
		this.vbox3.Add (this.entry5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry5]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry6 = new global::Gtk.Entry ();
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '•';
		this.vbox3.Add (this.entry6);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry6]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox3.Add (this.vbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
		w12.Position = 1;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entry7 = new global::Gtk.Entry ();
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '•';
		this.vbox2.Add (this.entry7);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entry7]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entry8 = new global::Gtk.Entry ();
		this.entry8.CanFocus = true;
		this.entry8.Name = "entry8";
		this.entry8.IsEditable = true;
		this.entry8.InvisibleChar = '•';
		this.vbox2.Add (this.entry8);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entry8]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entry9 = new global::Gtk.Entry ();
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '•';
		this.vbox2.Add (this.entry9);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entry9]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w18.Position = 1;
		this.notebook1.Add (this.hbox1);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Расчёт крепежа");
		this.notebook1.SetTabLabel (this.hbox1, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.image3 = new global::Gtk.Image ();
		this.image3.WidthRequest = 450;
		this.image3.HeightRequest = 320;
		this.image3.Name = "image3";
		this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Summer_work.Отсканированный документ-10.jpg");
		this.vbox5.Add (this.image3);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.image3]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.entry10 = new global::Gtk.Entry ();
		this.entry10.CanFocus = true;
		this.entry10.Name = "entry10";
		this.entry10.IsEditable = true;
		this.entry10.InvisibleChar = '•';
		this.vbox6.Add (this.entry10);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.entry10]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.entry11 = new global::Gtk.Entry ();
		this.entry11.CanFocus = true;
		this.entry11.Name = "entry11";
		this.entry11.IsEditable = true;
		this.entry11.InvisibleChar = '•';
		this.vbox6.Add (this.entry11);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.entry11]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.entry12 = new global::Gtk.Entry ();
		this.entry12.CanFocus = true;
		this.entry12.Name = "entry12";
		this.entry12.IsEditable = true;
		this.entry12.InvisibleChar = '•';
		this.vbox6.Add (this.entry12);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.entry12]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox5.Add (this.vbox6);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox6]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.hbox4.Add (this.vbox5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox5]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.entry13 = new global::Gtk.Entry ();
		this.entry13.CanFocus = true;
		this.entry13.Name = "entry13";
		this.entry13.IsEditable = true;
		this.entry13.InvisibleChar = '•';
		this.vbox7.Add (this.entry13);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.entry13]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.entry14 = new global::Gtk.Entry ();
		this.entry14.CanFocus = true;
		this.entry14.Name = "entry14";
		this.entry14.IsEditable = true;
		this.entry14.InvisibleChar = '•';
		this.vbox7.Add (this.entry14);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.entry14]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.entry15 = new global::Gtk.Entry ();
		this.entry15.CanFocus = true;
		this.entry15.Name = "entry15";
		this.entry15.IsEditable = true;
		this.entry15.InvisibleChar = '•';
		this.vbox7.Add (this.entry15);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.entry15]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.hbox4.Add (this.vbox7);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox7]));
		w29.Position = 1;
		this.notebook1.Add (this.hbox4);
		global::Gtk.Notebook.NotebookChild w30 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox4]));
		w30.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Расчёт фундамента");
		this.notebook1.SetTabLabel (this.hbox4, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.image4 = new global::Gtk.Image ();
		this.image4.WidthRequest = 250;
		this.image4.HeightRequest = 250;
		this.image4.Name = "image4";
		this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Summer_work.Отсканированный документ-10.jpg");
		this.hbox5.Add (this.image4);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.image4]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.entry16 = new global::Gtk.Entry ();
		this.entry16.CanFocus = true;
		this.entry16.Name = "entry16";
		this.entry16.IsEditable = true;
		this.entry16.InvisibleChar = '•';
		this.vbox8.Add (this.entry16);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.entry16]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.entry17 = new global::Gtk.Entry ();
		this.entry17.CanFocus = true;
		this.entry17.Name = "entry17";
		this.entry17.IsEditable = true;
		this.entry17.InvisibleChar = '•';
		this.vbox8.Add (this.entry17);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.entry17]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.entry18 = new global::Gtk.Entry ();
		this.entry18.CanFocus = true;
		this.entry18.Name = "entry18";
		this.entry18.IsEditable = true;
		this.entry18.InvisibleChar = '•';
		this.vbox8.Add (this.entry18);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.entry18]));
		w34.Position = 2;
		w34.Expand = false;
		w34.Fill = false;
		this.hbox5.Add (this.vbox8);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox8]));
		w35.Position = 1;
		this.table1.Add (this.hbox5);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox5]));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.image7 = new global::Gtk.Image ();
		this.image7.WidthRequest = 250;
		this.image7.HeightRequest = 250;
		this.image7.Name = "image7";
		this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Summer_work.Отсканированный документ-4.jpg");
		this.hbox6.Add (this.image7);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.image7]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.entry19 = new global::Gtk.Entry ();
		this.entry19.CanFocus = true;
		this.entry19.Name = "entry19";
		this.entry19.IsEditable = true;
		this.entry19.InvisibleChar = '•';
		this.vbox9.Add (this.entry19);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.entry19]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.entry20 = new global::Gtk.Entry ();
		this.entry20.CanFocus = true;
		this.entry20.Name = "entry20";
		this.entry20.IsEditable = true;
		this.entry20.InvisibleChar = '•';
		this.vbox9.Add (this.entry20);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.entry20]));
		w39.Position = 1;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.entry21 = new global::Gtk.Entry ();
		this.entry21.CanFocus = true;
		this.entry21.Name = "entry21";
		this.entry21.IsEditable = true;
		this.entry21.InvisibleChar = '•';
		this.vbox9.Add (this.entry21);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.entry21]));
		w40.Position = 2;
		w40.Expand = false;
		w40.Fill = false;
		this.hbox6.Add (this.vbox9);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox9]));
		w41.Position = 1;
		this.table1.Add (this.hbox6);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox6]));
		w42.TopAttach = ((uint)(1));
		w42.BottomAttach = ((uint)(2));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.image5 = new global::Gtk.Image ();
		this.image5.WidthRequest = 100;
		this.image5.HeightRequest = 150;
		this.image5.Name = "image5";
		this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Summer_work.Отсканированный документ-10.jpg");
		this.hbox8.Add (this.image5);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.image5]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.entry22 = new global::Gtk.Entry ();
		this.entry22.CanFocus = true;
		this.entry22.Name = "entry22";
		this.entry22.IsEditable = true;
		this.entry22.InvisibleChar = '•';
		this.vbox10.Add (this.entry22);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.entry22]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.entry23 = new global::Gtk.Entry ();
		this.entry23.CanFocus = true;
		this.entry23.Name = "entry23";
		this.entry23.IsEditable = true;
		this.entry23.InvisibleChar = '•';
		this.vbox10.Add (this.entry23);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.entry23]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.entry24 = new global::Gtk.Entry ();
		this.entry24.CanFocus = true;
		this.entry24.Name = "entry24";
		this.entry24.IsEditable = true;
		this.entry24.InvisibleChar = '•';
		this.vbox10.Add (this.entry24);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.entry24]));
		w46.Position = 2;
		w46.Expand = false;
		w46.Fill = false;
		this.hbox8.Add (this.vbox10);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox10]));
		w47.Position = 1;
		this.hbox7.Add (this.hbox8);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox8]));
		w48.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.image6 = new global::Gtk.Image ();
		this.image6.WidthRequest = 100;
		this.image6.HeightRequest = 150;
		this.image6.Name = "image6";
		this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Summer_work.Отсканированный документ-4.jpg");
		this.hbox9.Add (this.image6);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.image6]));
		w49.Position = 0;
		w49.Expand = false;
		w49.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.entry25 = new global::Gtk.Entry ();
		this.entry25.CanFocus = true;
		this.entry25.Name = "entry25";
		this.entry25.IsEditable = true;
		this.entry25.InvisibleChar = '•';
		this.vbox11.Add (this.entry25);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.entry25]));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.entry26 = new global::Gtk.Entry ();
		this.entry26.CanFocus = true;
		this.entry26.Name = "entry26";
		this.entry26.IsEditable = true;
		this.entry26.InvisibleChar = '•';
		this.vbox11.Add (this.entry26);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.entry26]));
		w51.Position = 1;
		w51.Expand = false;
		w51.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.entry27 = new global::Gtk.Entry ();
		this.entry27.CanFocus = true;
		this.entry27.Name = "entry27";
		this.entry27.IsEditable = true;
		this.entry27.InvisibleChar = '•';
		this.vbox11.Add (this.entry27);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.entry27]));
		w52.Position = 2;
		w52.Expand = false;
		w52.Fill = false;
		this.hbox9.Add (this.vbox11);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox11]));
		w53.Position = 1;
		this.hbox7.Add (this.hbox9);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox9]));
		w54.Position = 1;
		this.table1.Add (this.hbox7);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox7]));
		w55.LeftAttach = ((uint)(1));
		w55.RightAttach = ((uint)(2));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.entry28 = new global::Gtk.Entry ();
		this.entry28.CanFocus = true;
		this.entry28.Name = "entry28";
		this.entry28.IsEditable = true;
		this.entry28.InvisibleChar = '•';
		this.vbox12.Add (this.entry28);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.entry28]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.entry29 = new global::Gtk.Entry ();
		this.entry29.CanFocus = true;
		this.entry29.Name = "entry29";
		this.entry29.IsEditable = true;
		this.entry29.InvisibleChar = '•';
		this.vbox12.Add (this.entry29);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.entry29]));
		w57.Position = 1;
		w57.Expand = false;
		w57.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.entry30 = new global::Gtk.Entry ();
		this.entry30.CanFocus = true;
		this.entry30.Name = "entry30";
		this.entry30.IsEditable = true;
		this.entry30.InvisibleChar = '•';
		this.vbox12.Add (this.entry30);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.entry30]));
		w58.Position = 2;
		w58.Expand = false;
		w58.Fill = false;
		this.table1.Add (this.vbox12);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox12]));
		w59.TopAttach = ((uint)(1));
		w59.BottomAttach = ((uint)(2));
		w59.LeftAttach = ((uint)(1));
		w59.RightAttach = ((uint)(2));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook1.Add (this.table1);
		global::Gtk.Notebook.NotebookChild w60 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.table1]));
		w60.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Расчёт пеноблоков и кирпичей");
		this.notebook1.SetTabLabel (this.table1, this.label3);
		this.label3.ShowAll ();
		this.hbox2.Add (this.notebook1);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.notebook1]));
		w61.Position = 1;
		this.Add (this.hbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1022;
		this.DefaultHeight = 539;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
